language: rust
sudo: false
env: RUST_BACKTRACE=1

before_script:
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
  - docker pull marwes/try_gluon || true

script:
  - docker build --tag try_gluon .
  - docker run try_gluon cargo test --release

after_script:
  - docker images

before_deploy:
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"

deploy:
  provider: script
  script: docker push marwes/try_gluon
  on:
    branch: test
