[package]
name = "try_gluon"
version = "0.5.0"
authors = ["Markus <marwes91@gmail.com>"]

license = "MIT"

[workspace]
members = ["gluon_master"]

[[bin]]
name = "try_gluon"
path = "src/app/main.rs"

[dependencies]
env_logger = "0.5"
failure = "0.1"
futures = "0.1.0"
hubcaps = { git = "https://github.com/softprops/hubcaps", rev = "12ee80d" }
log = "0.4"
serde = "1"
serde_derive = "1"
serde_json = "1"
structopt = "0.2"
tokio = "0.1"
hyper = "0.12"
hyper-tls = "0.3"

gluon = { version = "0.9.3", features = ["serialization", "web", "regex", "rand"] }
gluon_format = { version = "0.9.3" }
gluon_vm = { version = "0.9.3" }
gluon_codegen = { version = "0.9.3" }

gluon_master = { path = "gluon_master" }

[build-dependencies]
failure = "0.1"
glob = "0.2"
home = "0.3"
regex = "1"

gluon_master = { path = "gluon_master" }

[dev-dependencies]
tokio-retry = "0.2"

# [patch.crates-io]
# gluon_codegen = { path = "../gluon/codegen" }
# gluon_format = { path = "../gluon/format" }
# gluon_vm = { path = "../gluon/vm" }
# gluon = { path = "../gluon" }
# gluon_codegen = { git = "https://github.com/Marwes/gluon", branch = "https" }
# gluon_format = { git = "https://github.com/Marwes/gluon", branch = "https" }
# gluon_vm = { git = "https://github.com/Marwes/gluon", branch = "https" }
# gluon = { git = "https://github.com/Marwes/gluon", branch = "https" }
